general:
  data_base_dir: /app/data
  version: 1.0
  description: "Default configuration for MONAIAuto3dSeg (dicom in, dicom out)"

execute:
- DicomImporter
- NiftiConverter
- A3DS_Vertebrae_Runner
- DsegConverter
- DataOrganizer

modules:
  DicomImporter:
    source_dir: input_data
    import_dir: sorted_data
    sort_data: True
    meta: 
      mod: '%Modality'

  DsegConverter:
    model_name: a3ds-vertebrae
    body_part_examined: VERTEBRA
    source_segs: nifti:mod=seg
    json_config_path: /app/models/a3ds-vertebrae/config/auto-gen-auto3dseg.json
 
    skip_empty_slices: True
  
  DataOrganizer:
    targets:
    - dicomseg:mod=seg-->[i:sid]/a3ds-vertebrae.seg.dcm
